project = "test-terraform-405913"
credentials_project = "../keys/test-terraform-sa.json"
network = "default"
public_key_vm = "../keys/terraform-key.pub"
private_key_vm = "../keys/terraform-key"
user_gcp = "riswanda_work"